apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.activeService.name }}
  labels:
    {{- include "hello-world.labels" . | nindent 4 }}
spec:
  type: {{ .Values.activeService.type }}
  ports:
    - port: {{ .Values.activeService.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "hello-world.selectorLabels" . | nindent 4 }}
